### ISSUE TITLE
Some core nodes are not in the original node list

### ISSUE THREAD

**Issue by ChengMa-RPI** [arbenson/FGDnPVC#2]
Hi,

I just found that the data of call-Reality and core-call-Reality are not consistent. Some nodes in core-call Reality dataset, for example node ID 7, don't appear in the call-Reality dataset. I think core-call Reality should be a subset of call-Reality. Am I right? 

Thank you and appreciate your help!

**Comment by arbenson** [comment]
Hi,

Thanks for raising the issue. Some individuals were listed as participants in the study but did not send or receive a call, at least from what is recorded in the data. Node 7 is one such node (it might be the only one not participating in a phone call). I had this in the README of for the text-Reality dataset, but not this one. I updated the readme here:
https://github.com/arbenson/FGDnPVC/commit/09289a9f0ebade626b06e7b150c78160e39c6c2b

**Comment by ChengMa-RPI** [comment]
Than you for addressing this problem!
